<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-06T17:01:47 BDT" name="Default suite" finished-at="2021-09-06T17:01:51 BDT" duration-ms="3844">
    <groups>
    </groups>
    <test started-at="2021-09-06T17:01:47 BDT" name="Default test" finished-at="2021-09-06T17:01:51 BDT" duration-ms="3844">
      <class name="title_backend.VerifyTitle">
        <test-method is-config="true" signature="setDriver()[pri:0, instance:title_backend.VerifyTitle@1530c739]" started-at="2021-09-06T17:01:45 BDT" name="setDriver" finished-at="2021-09-06T17:01:47 BDT" duration-ms="1654" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDriver -->
        <test-method signature="TitleTest()[pri:0, instance:title_backend.VerifyTitle@1530c739]" started-at="2021-09-06T17:01:47 BDT" name="TitleTest" finished-at="2021-09-06T17:01:51 BDT" duration-ms="3784" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Do not execute further steps]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Do not execute further steps
at title_backend.VerifyTitle.TitleTest(VerifyTitle.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TitleTest -->
        <test-method is-config="true" signature="close()[pri:0, instance:title_backend.VerifyTitle@1530c739]" started-at="2021-09-06T17:01:51 BDT" name="close" finished-at="2021-09-06T17:01:51 BDT" duration-ms="134" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- title_backend.VerifyTitle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
